# Generated by Django 5.2.15 on 2026-07-05 11:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dictionary", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "item_type",
                    models.CharField(
                        choices=[("word", "Word"), ("kanji", "Kanji"), ("kana", "Kana")],
                        max_length=8,
                    ),
                ),
                ("stability", models.FloatField(blank=True, null=True)),
                ("difficulty", models.FloatField(blank=True, null=True)),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "New"), (1, "Learning"), (2, "Review"), (3, "Relearning")],
                        default=0,
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("due", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_review", models.DateTimeField(blank=True, null=True)),
                ("reps", models.PositiveIntegerField(default=0)),
                ("lapses", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "kana",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kana",
                    ),
                ),
                (
                    "kanji",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.kanji",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "srs_cards",
                "ordering": ["due"],
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("rating", models.PositiveSmallIntegerField()),
                ("state_before", models.PositiveSmallIntegerField()),
                ("stability", models.FloatField(blank=True, null=True)),
                ("difficulty", models.FloatField(blank=True, null=True)),
                ("elapsed_days", models.FloatField(default=0.0)),
                ("scheduled_days", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("reviewed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="srs.card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "srs_review_logs",
                "ordering": ["-reviewed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["user", "due"], name="srs_cards_user_id_f8b43e_idx"),
        ),
        migrations.AddIndex(
            model_name="card",
            index=models.Index(fields=["user", "state"], name="srs_cards_user_id_de5486_idx"),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                condition=models.Q(("word__isnull", False)),
                fields=("user", "word"),
                name="uq_card_user_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kanji__isnull", False)),
                fields=("user", "kanji"),
                name="uq_card_user_kanji",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kana__isnull", False)),
                fields=("user", "kana"),
                name="uq_card_user_kana",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kana__isnull", True), ("kanji__isnull", True), ("word__isnull", False)
                    ),
                    models.Q(
                        ("kana__isnull", True), ("kanji__isnull", False), ("word__isnull", True)
                    ),
                    models.Q(
                        ("kana__isnull", False), ("kanji__isnull", True), ("word__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="card_exactly_one_item",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["user", "reviewed_at"], name="srs_review__user_id_75430f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewlog",
            index=models.Index(
                fields=["card", "reviewed_at"], name="srs_review__card_id_115bd5_idx"
            ),
        ),
    ]
