# Generated by Django 5.2.15 on 2026-07-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
