# Generated by Django 5.2.15 on 2026-07-16 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0004_card_source_context'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoosterGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_id', models.CharField(max_length=64)),
                ('source', models.CharField(default='streak_milestone', max_length=32)),
                ('milestone', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('unopened', 'Unopened'), ('opened', 'Opened'), ('skipped_full', 'Skipped Full')], default='unopened', max_length=16)),
                ('granted_at', models.DateTimeField()),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('cards', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booster_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srs_booster_grants',
                'constraints': [models.UniqueConstraint(fields=('user', 'grant_id'), name='uq_booster_user_grant')],
            },
        ),
        migrations.CreateModel(
            name='CollectionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=64)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_obtained_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srs_collection_cards',
                'constraints': [models.UniqueConstraint(fields=('user', 'card_id'), name='uq_collection_user_card')],
            },
        ),
    ]
