# Generated by Django 5.2.15 on 2026-09-06 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("srs", "0005_boostergrant_collectioncard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewlog",
            name="client_review_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="reviewlog",
            constraint=models.UniqueConstraint(
                fields=("user", "client_review_id"), name="uq_review_user_client"
            ),
        ),
    ]
