# Generated by Django 5.2.15 on 2026-07-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Radical",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("literal", models.CharField(max_length=4, unique=True)),
                ("strokes", models.PositiveSmallIntegerField(default=0)),
                ("reading", models.CharField(blank=True, max_length=32)),
                ("meaning", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "dict_radicals",
                "ordering": ["strokes", "literal"],
            },
        ),
        migrations.CreateModel(
            name="Kana",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("char", models.CharField(max_length=4, unique=True)),
                ("romaji", models.CharField(max_length=8)),
                (
                    "script",
                    models.CharField(
                        choices=[("hiragana", "Hiragana"), ("katakana", "Katakana")], max_length=10
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("gojuon", "Gojūon"),
                            ("dakuten", "Dakuten"),
                            ("handakuten", "Handakuten"),
                            ("yoon", "Yōon"),
                        ],
                        default="gojuon",
                        max_length=12,
                    ),
                ),
                ("row", models.CharField(blank=True, max_length=4)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "dict_kana",
                "ordering": ["script", "order"],
                "indexes": [
                    models.Index(fields=["script", "kind"], name="dict_kana_script_f28fb1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Kanji",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("literal", models.CharField(max_length=4, unique=True)),
                ("grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("stroke_count", models.PositiveSmallIntegerField(default=0)),
                ("jlpt", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("freq_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("radical_number", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("on_readings", models.JSONField(blank=True, default=list)),
                ("kun_readings", models.JSONField(blank=True, default=list)),
                ("nanori", models.JSONField(blank=True, default=list)),
                ("components", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "dict_kanji",
                "ordering": ["freq_rank", "stroke_count", "literal"],
                "indexes": [
                    models.Index(fields=["jlpt"], name="dict_kanji_jlpt_775295_idx"),
                    models.Index(fields=["grade"], name="dict_kanji_grade_5b21f7_idx"),
                    models.Index(fields=["freq_rank"], name="dict_kanji_freq_ra_2c02fc_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Word",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("seq", models.BigIntegerField(blank=True, null=True, unique=True)),
                ("is_common", models.BooleanField(default=False)),
                ("jlpt", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("freq_rank", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "dict_words",
                "indexes": [
                    models.Index(
                        fields=["is_common", "freq_rank"], name="dict_words_is_comm_57b4e7_idx"
                    ),
                    models.Index(fields=["jlpt"], name="dict_words_jlpt_06502d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Sense",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("pos", models.JSONField(blank=True, default=list)),
                ("misc", models.JSONField(blank=True, default=list)),
                ("field", models.JSONField(blank=True, default=list)),
                ("info", models.CharField(blank=True, max_length=255)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="senses",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "dict_senses",
                "ordering": ["word", "order"],
            },
        ),
        migrations.CreateModel(
            name="KanjiMeaning",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lang", models.CharField(default="en", max_length=8)),
                ("text", models.CharField(max_length=128)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "kanji",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meanings",
                        to="dictionary.kanji",
                    ),
                ),
            ],
            options={
                "db_table": "dict_kanji_meanings",
                "ordering": ["kanji", "order"],
                "indexes": [
                    models.Index(fields=["lang", "text"], name="dict_kanji__lang_53ea8b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Gloss",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lang", models.CharField(default="en", max_length=8)),
                ("text", models.CharField(max_length=255)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "sense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glosses",
                        to="dictionary.sense",
                    ),
                ),
            ],
            options={
                "db_table": "dict_glosses",
                "ordering": ["sense", "order"],
                "indexes": [
                    models.Index(fields=["lang", "text"], name="dict_glosse_lang_d7fe9f_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WordForm",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(choices=[("kanji", "Kanji"), ("kana", "Kana")], max_length=8),
                ),
                ("is_common", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forms",
                        to="dictionary.word",
                    ),
                ),
            ],
            options={
                "db_table": "dict_word_forms",
                "ordering": ["word", "kind", "order"],
                "indexes": [
                    models.Index(fields=["text"], name="dict_word_f_text_6eff54_idx"),
                    models.Index(fields=["kind", "text"], name="dict_word_f_kind_7d9bd6_idx"),
                ],
            },
        ),
    ]
