# Generated by Django 5.2.15 on 2026-07-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_search_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('japanese', models.TextField()),
                ('english', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'dict_examples',
            },
        ),
        migrations.AddField(
            model_name='wordform',
            name='pitch',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('kanji', models.CharField(blank=True, max_length=64)),
                ('reading', models.CharField(max_length=64)),
                ('translations', models.JSONField(blank=True, default=list)),
                ('name_types', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'dict_names',
                'indexes': [models.Index(fields=['reading'], name='dict_names_reading_27a633_idx'), models.Index(fields=['kanji'], name='dict_names_kanji_107ade_idx')],
            },
        ),
    ]
