# Generated by Django 5.2.15 on 2026-07-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_examples_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='kana',
            name='origin',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='kana',
            name='origin_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kanji',
            name='formation',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='kanji',
            name='origin',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kanji',
            name='phonetic',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
