# Generated by Django 5.2.15 on 2026-07-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_kana_origin_kana_origin_note_kanji_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kana',
            name='usage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kana',
            name='usage_label',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
