# Generated by Django 5.2.15 on 2026-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0009_normalize_localized_content"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="gloss",
            name="dict_glosse_lang_d7fe9f_idx",
        ),
        migrations.RemoveIndex(
            model_name="kanjimeaning",
            name="dict_kanji__lang_53ea8b_idx",
        ),
        migrations.RemoveIndex(
            model_name="nametranslation",
            name="dict_name_t_languag_f34c86_idx",
        ),
        migrations.AddField(
            model_name="examplesentence",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="examplesentence",
            name="source_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gloss",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="kanji",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="kanji",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="name",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="name",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sense",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="word",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="wordform",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="gloss",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="kanjimeaning",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="nametranslation",
            name="text",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="sensenote",
            name="text",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="gloss",
            index=models.Index(fields=["language"], name="dict_glosse_lang_d7fe9f_idx"),
        ),
        migrations.AddIndex(
            model_name="kanjimeaning",
            index=models.Index(fields=["language"], name="dict_kanji__lang_53ea8b_idx"),
        ),
        migrations.AddIndex(
            model_name="nametranslation",
            index=models.Index(fields=["language"], name="dict_name_t_languag_f34c86_idx"),
        ),
    ]
