# Generated by Django 5.2.15 on 2026-09-09 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0010_source_metadata_and_lossless_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExampleSenseLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(default="jmdict", max_length=32)),
                ("source_sense_order", models.PositiveSmallIntegerField()),
                ("text", models.TextField(blank=True)),
                ("provenance", models.JSONField(blank=True, default=dict)),
                (
                    "example",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sense_links",
                        to="dictionary.examplesentence",
                    ),
                ),
                (
                    "sense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_links",
                        to="dictionary.sense",
                    ),
                ),
            ],
            options={
                "db_table": "dict_example_sense_links",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("example", "sense", "source"), name="uq_example_sense_source"
                    )
                ],
            },
        ),
    ]
