# Generated by Django 5.2.15 on 2026-09-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0012_kana_word_examples"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="canonical_word",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_aliases",
                to="dictionary.word",
            ),
        ),
    ]
