# Generated by Django 5.2.15 on 2026-07-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="fsrs_parameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
