# Generated by Django 5.2.15 on 2026-07-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_active_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('lifetime', 'Lifetime')], default='lifetime', max_length=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
