# Generated by Django 5.2.15 on 2026-07-05 11:34

import django.db.models.deletion
import mnemonics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mnemonic",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("character", models.CharField(max_length=4)),
                (
                    "kind",
                    models.CharField(choices=[("kana", "Kana"), ("kanji", "Kanji")], max_length=8),
                ),
                ("language", models.CharField(default="en", max_length=8)),
                ("story", models.TextField()),
                (
                    "image",
                    models.FileField(blank=True, upload_to=mnemonics.models.mnemonic_image_path),
                ),
                ("image_width", models.PositiveIntegerField(default=0)),
                ("image_height", models.PositiveIntegerField(default=0)),
                ("is_seed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("visible", "Visible"),
                            ("pending", "Pending review"),
                            ("hidden", "Hidden"),
                            ("removed", "Removed"),
                        ],
                        default="visible",
                        max_length=10,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("moderation_note", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mnemonics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonics",
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MnemonicReport",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("offensive", "Offensive or explicit"),
                            ("inaccurate", "Inaccurate or misleading"),
                            ("spam", "Spam or advertising"),
                            ("off_topic", "Off-topic"),
                            ("other", "Something else"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("detail", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                            ("actioned", "Actioned"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mnemonic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="mnemonics.mnemonic",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonic_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MnemonicVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.SmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mnemonic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="mnemonics.mnemonic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonic_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_votes",
            },
        ),
        migrations.AddIndex(
            model_name="mnemonic",
            index=models.Index(
                fields=["kind", "character", "language", "status"], name="mnemonics_kind_2b9fad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonic",
            index=models.Index(
                fields=["character", "language", "score"], name="mnemonics_charact_900ea3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonic",
            index=models.Index(fields=["status"], name="mnemonics_status_00d437_idx"),
        ),
        migrations.AddIndex(
            model_name="mnemonicreport",
            index=models.Index(
                fields=["status", "created_at"], name="mnemonic_re_status_1012c6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mnemonicreport",
            constraint=models.UniqueConstraint(
                fields=("mnemonic", "reporter"), name="uq_report_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="mnemonicvote",
            constraint=models.UniqueConstraint(
                fields=("mnemonic", "user"), name="uq_vote_per_user"
            ),
        ),
    ]
