# Generated by Django 5.2.15 on 2026-07-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mnemonics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MnemonicDeck",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("language", models.CharField(default="en", max_length=8)),
                (
                    "kind",
                    models.CharField(
                        choices=[("kana", "Kana"), ("kanji", "Kanji")], default="kana", max_length=8
                    ),
                ),
                ("is_seed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending review"),
                            ("visible", "Visible"),
                            ("hidden", "Hidden"),
                            ("removed", "Removed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hidden_at", models.DateTimeField(blank=True, null=True)),
                ("moderation_note", models.TextField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mnemonic_decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_decks",
                "ordering": ["-score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MnemonicDeckItem",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="mnemonics.mnemonicdeck",
                    ),
                ),
                (
                    "mnemonic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck_items",
                        to="mnemonics.mnemonic",
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_deck_items",
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddField(
            model_name="mnemonicdeck",
            name="mnemonics",
            field=models.ManyToManyField(
                related_name="decks", through="mnemonics.MnemonicDeckItem", to="mnemonics.mnemonic"
            ),
        ),
        migrations.CreateModel(
            name="MnemonicDeckVote",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("value", models.SmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="mnemonics.mnemonicdeck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonic_deck_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_deck_votes",
            },
        ),
        migrations.CreateModel(
            name="MnemonicSave",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mnemonic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="mnemonics.mnemonic",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mnemonic_saves",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "mnemonic_saves",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="mnemonicdeckitem",
            constraint=models.UniqueConstraint(
                fields=("deck", "mnemonic"), name="uq_deck_mnemonic"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonicdeck",
            index=models.Index(
                fields=["status", "language", "kind"], name="mnemonic_de_status_4b83dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonicdeck",
            index=models.Index(
                fields=["language", "kind", "score"], name="mnemonic_de_languag_61c2bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonicdeck",
            index=models.Index(fields=["status"], name="mnemonic_de_status_69fa98_idx"),
        ),
        migrations.AddConstraint(
            model_name="mnemonicdeckvote",
            constraint=models.UniqueConstraint(
                fields=("deck", "user"), name="uq_deck_vote_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="mnemonicsave",
            index=models.Index(
                fields=["user", "created_at"], name="mnemonic_sa_user_id_289ed3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mnemonicsave",
            constraint=models.UniqueConstraint(
                fields=("mnemonic", "user"), name="uq_save_per_user"
            ),
        ),
    ]
