# Generated by Django 5.2.15 on 2026-07-05 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnemonics', '0002_mnemonicdeck_mnemonicdeckitem_mnemonicdeck_mnemonics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMnemonicChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('kana', 'Kana'), ('kanji', 'Kanji')], max_length=8)),
                ('character', models.CharField(max_length=4)),
                ('language', models.CharField(default='en', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mnemonic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by', to='mnemonics.mnemonic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mnemonic_choices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mnemonic_choices',
                'indexes': [models.Index(fields=['user', 'kind', 'language'], name='mnemonic_ch_user_id_1d1175_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'character', 'language'), name='uq_choice_per_char')],
            },
        ),
    ]
