# Generated by Django 5.2.15 on 2026-07-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mnemonics', '0003_usermnemonicchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mnemonic',
            name='reading',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='mnemonic',
            name='kind',
            field=models.CharField(choices=[('kana', 'Kana'), ('kanji', 'Kanji'), ('kanji_reading', 'Kanji reading')], max_length=16),
        ),
        migrations.AlterField(
            model_name='mnemonicdeck',
            name='kind',
            field=models.CharField(choices=[('kana', 'Kana'), ('kanji', 'Kanji'), ('kanji_reading', 'Kanji reading')], default='kana', max_length=16),
        ),
        migrations.AlterField(
            model_name='usermnemonicchoice',
            name='kind',
            field=models.CharField(choices=[('kana', 'Kana'), ('kanji', 'Kanji'), ('kanji_reading', 'Kanji reading')], max_length=16),
        ),
    ]
