# Generated by Django 5.2.15 on 2026-07-09 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("bug", "Bug"),
                            ("love", "Love"),
                            ("other", "Other"),
                        ],
                        max_length=8,
                    ),
                ),
                ("message", models.TextField(max_length=4000)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "New"), ("seen", "Seen"), ("done", "Done")],
                        default="new",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "feedback",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="feedback_status_90e99d_idx")
                ],
            },
        ),
    ]
