# Generated by Django 5.2.15 on 2026-07-09 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('kanji', 'Kanji'), ('kana', 'Kana'), ('word', 'Word')], max_length=8)),
                ('item_ref', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('wrong', 'Something is wrong'), ('missing', 'Something is missing'), ('typo', 'Typo or formatting'), ('other', 'Something else')], default='other', max_length=8)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen'), ('done', 'Done')], default='new', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'content_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='content_rep_status_c435df_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'item_type', 'item_ref'), name='uq_content_report_per_user')],
            },
        ),
    ]
